// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetClinic.Data;

#nullable disable

namespace Vet_Clinic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251121233704_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VetClinic.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MicrochipId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VetDoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VetDoctorId");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MicrochipId = "MC001",
                            Name = "Buddy",
                            Species = "Dog",
                            VetDoctorId = 1
                        },
                        new
                        {
                            Id = 2,
                            MicrochipId = "MC002",
                            Name = "Mittens",
                            Species = "Cat",
                            VetDoctorId = 2
                        },
                        new
                        {
                            Id = 3,
                            MicrochipId = "MC003",
                            Name = "Luna",
                            Species = "Cat",
                            VetDoctorId = 2
                        },
                        new
                        {
                            Id = 4,
                            MicrochipId = "MC004",
                            Name = "Kiwi",
                            Species = "Parrot",
                            VetDoctorId = 3
                        });
                });

            modelBuilder.Entity("VetClinic.Models.PetProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<string>("VetNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("PetProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PetId = 1,
                            VetNotes = "Healthy. Annual checkup done."
                        },
                        new
                        {
                            Id = 2,
                            PetId = 2,
                            VetNotes = "Allergy to food. Monitor diet."
                        },
                        new
                        {
                            Id = 3,
                            PetId = 3,
                            VetNotes = "Vaccinated. Monitor side effects."
                        },
                        new
                        {
                            Id = 4,
                            PetId = 4,
                            VetNotes = "Feathers trimmed. Follow-up in 3 months."
                        });
                });

            modelBuilder.Entity("VetClinic.Models.VetDoctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VetDoctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dr. Alice",
                            Specialty = "Dogs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dr. Bob",
                            Specialty = "Cats"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dr. Maria",
                            Specialty = "Birds & Exotics"
                        });
                });

            modelBuilder.Entity("VetClinic.Models.Pet", b =>
                {
                    b.HasOne("VetClinic.Models.VetDoctor", "VetDoctor")
                        .WithMany()
                        .HasForeignKey("VetDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VetDoctor");
                });

            modelBuilder.Entity("VetClinic.Models.PetProfile", b =>
                {
                    b.HasOne("VetClinic.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
